# -*- coding: utf-8 -*-
"""Ethane.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NLwUf-EZPJkv_uLF7vJ4TXKZ0_8KWGgy
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from google.colab import files 
  
  
uploaded = files.upload()

import io 
  
ethane_df = pd.read_csv(io.BytesIO(uploaded['Ethane - Sheet1.csv'])) 
print(ethane_df)

sns.scatterplot(data=ethane_df, x="Dihedral Angles", y="Potential Energy")

sns.jointplot(x="Dihedral Angles", y="Potential Energy", data=ethane_df, kind="scatter")

sns.pairplot(ethane_df)