# -*- coding: utf-8 -*-
"""Golden_Section_Method_BIM-2019-18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-L6wjj6RCjEmyz3IvF8MBC3FF9zmwQIz
"""

from scipy import optimize

def f(x):
  return x**2 - 4*x -10

a = int(input("Enter a value for a: "))
b = int(input("Enter a value for b: "))

minimum = optimize.golden(f, brack=(a, b))
print(minimum)