# -*- coding: utf-8 -*-
"""Water.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SWqMBXDtxEZLa4VI2rMPa9gqnlJOAkCP
"""

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from google.colab import files #this is for Google Colab usage only
  
  
uploaded = files.upload() ####

import pandas as pd 
import io 
  
water_df = pd.read_csv(io.BytesIO(uploaded['Water - Sheet1.csv'])) 
print(water_df)

df=water_df.unstack().reset_index()
df.columns=["Potential Energy","BL","BA"]

df['Potential Energy']=pd.Categorical(df['Potential Energy'])
df['Potential Energy']=df['Potential Energy'].cat.codes
df['BL']=pd.Categorical(df['BL'])
df['BL']=df['BL'].cat.codes
df['BA']=pd.Categorical(df['BA'])
df['BA']=df['BA'].cat.codes

fig = plt.figure()
ax = fig.gca(projection='3d')
ax.plot_trisurf(df['BL'], df['Potential Energy'], df['BA'], cmap=plt.cm.jet, linewidth=0.2)
fig.colorbar( surf, shrink=0.5, aspect=5)
#ax.view_init(30, 45)
plt.show()

fig = plt.figure()
ax = fig.gca(projection='3d')
ax.plot_trisurf(df['BL'], df['Potential Energy'], df['BA'], cmap=plt.cm.jet, linewidth=0.2)
fig.colorbar( surf, shrink=0.5, aspect=5)
ax.view_init(30, 45)
plt.show()
